#!/usr/bin/env python
"""Create a deterministic WebGPU parity/latency case for the history encoder.

This reuses the exact fixed-shape ONNX graph loaded by the infinite demo. The
reference is generated by native ONNX Runtime CPU, so no model re-export and no
package installation are required.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np
import onnx
import onnxruntime as ort


TOY_ROOT = Path(__file__).resolve().parents[1]
CASE_ID = "ardy_history_encoder_fp32"
CASE_DIR = TOY_ROOT / "cases" / CASE_ID
MODEL_PATH = TOY_ROOT / "infinite_demo" / "models" / "shared" / "encode_history.onnx"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> None:
    CASE_DIR.mkdir(parents=True, exist_ok=True)
    count = 4 * 330
    index = np.arange(count, dtype=np.float32)
    normalized_history = (
        np.sin(index * np.float32(0.017)) * np.float32(0.35)
        + np.cos(index * np.float32(0.0031)) * np.float32(0.08)
    ).reshape(1, 4, 330)
    normalized_history.tofile(CASE_DIR / "input_normalized_history.bin")

    session = ort.InferenceSession(str(MODEL_PATH), providers=["CPUExecutionProvider"])
    output_names = [item.name for item in session.get_outputs()]
    values = session.run(output_names, {"normalized_history": normalized_history})
    tolerances = {
        "local_history": {
            "max_abs_error": 0.04,
            "mean_abs_error": 0.003,
            "min_cosine_similarity": 0.9999,
        },
        "global_translation": {
            "max_abs_error": 0.005,
            "mean_abs_error": 0.002,
            "min_cosine_similarity": 0.99999,
        },
        "first_heading_angle": {
            "max_abs_error": 0.005,
            "mean_abs_error": 0.002,
            "min_cosine_similarity": 0.99999,
        },
    }
    outputs = []
    for name, value in zip(output_names, values, strict=True):
        value = np.asarray(value, dtype=np.float32)
        filename = f"reference_{name}.bin"
        value.tofile(CASE_DIR / filename)
        outputs.append(
            {
                "name": name,
                "dtype": "float32",
                "shape": list(value.shape),
                "reference_url": f"cases/{CASE_ID}/{filename}",
                "compare_url": f"/api/compare/{CASE_ID}/{name}",
                "tolerances": tolerances[name],
            }
        )

    graph = onnx.load(MODEL_PATH)
    onnx.checker.check_model(graph)
    manifest = {
        "id": CASE_ID,
        "title": "ARDY Core history encoder FP32 / 4 frames",
        "description": "无限前端实际图；[1,4,330] explicit motion 到 [1,1,148] hybrid history；无 Llama。",
        "model_url": "infinite_demo/models/shared/encode_history.onnx",
        "model_sha256": sha256(MODEL_PATH),
        "model_size_bytes": MODEL_PATH.stat().st_size,
        "opset": 17,
        "operators": sorted({node.op_type for node in graph.graph.node}),
        "inputs": [
            {
                "name": "normalized_history",
                "dtype": "float32",
                "shape": [1, 4, 330],
                "url": f"cases/{CASE_ID}/input_normalized_history.bin",
            }
        ],
        "outputs": outputs,
        "tolerances": tolerances,
        "benchmark": {"warmup_runs": 3, "timed_runs": 20},
        "text_encoder_loaded": False,
    }
    (CASE_DIR / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    index_path = TOY_ROOT / "cases" / "index.json"
    case_index = json.loads(index_path.read_text(encoding="utf-8"))
    case_index["cases"] = [item for item in case_index["cases"] if item["id"] != CASE_ID]
    case_index["cases"].append(
        {
            "id": CASE_ID,
            "title": manifest["title"],
            "manifest_url": f"cases/{CASE_ID}/manifest.json",
        }
    )
    index_path.write_text(json.dumps(case_index, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"CASE={CASE_ID}")
    print(f"MODEL_SIZE={manifest['model_size_bytes']}")
    for output in outputs:
        print(f"OUTPUT={output['name']} shape={output['shape']}")


if __name__ == "__main__":
    main()
